name: Upstream Sync
permissions: write-all

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    outputs:
      has_changes: ${{ steps.sync.outputs.has_new_commits }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: 同步上游更新
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: perfect-panel/ppanel-web
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          test_mode: false

      - name: 检查同步
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '🚨 同步失败 | Sync Fail'
          labels: '🚨 Sync Fail'
          body: |
            // ...existing code...
            
